server:
  port:
    8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}/eureka/

